name: Build GHPR Leaderboard Project
on: 
  push:
    branches: main

jobs:
    build-image:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            
            - name: Read version from version.yaml
              id: read_version
              run: |
                VERSION=$(cat version.yaml | grep version | awk '{print $2}')
                echo "VERSION=$VERSION" >> $GITHUB_ENV
                 
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
            
            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKER_LOGIN }}
                password: ${{ secrets.DOCKER_PAT }}
            
            - name: Build and push Docker image
              uses: docker/build-push-action@v4
              with:
                context: .
                push: true
                tags: ${{ secrets.DOCKER_LOGIN }}/ghpr-leaderboard-report:${{ env.VERSION }}
              
            - name: Create Git tag
              id: tag
              run: |
                  git tag ${{ env.VERSION }}
                  git push origin ${{ env.VERSION }}
        
            - name: Create GitHub Release
              uses: actions/create-release@v1
              with:
                  tag_name: ${{ env.VERSION }}
                  release_name: Release ${{ env.VERSION }}
                  body: |
                    Changes in this release:
                    - Docker image published
                  draft: false
                  prerelease: false
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
            
