name: Build GHPR Leaderboard Project
on: 
  pull_request:
    branches: main

env:
    GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
    SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
    build-image:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
              
            - name: Build Docker image
              run: |
                ls -lart
                docker build -t ghpr-leaderboard-report:v0.0.1 .
            
            - name: Run Docker container
              run: |
                docker run -d -e GH_ACCESS_TOKEN=${{ env.GH_ACCESS_TOKEN }} -e SLACK_WEBHOOK_URL=${{ env.SLACK_WEBHOOK_URL }} --name ghpr-leaderboard-report ghpr-leaderboard-report:v0.0.1