name: Build GHPR Leaderboard Project
on: 
  push:
    branches: main

env:
    GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
    SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
    build-image:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
              
            - name: Print env variables
              run: |
                echo ${{ env.GH_ACCESS_TOKEN }}   
                echo ${{ env.SLACK_WEBHOOK_URL }}
            
            - name: Build Docker image
              run: |
                docker build -t ghpr-leaderboard-report:v0.0.1 .
            
            - name: Run Trivy vulnerability scanner
              uses: aquasecurity/trivy-action@0.20.0
              with:
                image-ref: 'docker.io/my-organization/my-app:${{ github.sha }}'
                format: 'sarif'
                output: 'trivy-results.sarif'
        
            - name: Upload Trivy scan results to GitHub Security tab
              uses: github/codeql-action/upload-sarif@v2
              with:
                sarif_file: 'trivy-results.sarif'